"""
Centralised configuration for the `lake` package.

Why a dedicated module?
-----------------------
The original notebook-style code scattered paths ("./data/dataset.csv",
"./EXPs/..."), hyperparameters (`batch_size=256`, `lr=0.005`), and magic
constants (the `/10000` target scaling, the `2683` lake count) across many
files. That makes the code hard to reuse from a CLI or to test.

This module centralises all of that. Every other module in the package
accepts a :class:`LakeConfig` (or pieces of it) so behaviour can be changed
without editing source code — either by mutating the dataclass in Python or
by loading a YAML file at runtime.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import List, Optional

import yaml


# ---------------------------------------------------------------------------
# Constants that genuinely belong in code (not user-tweakable per-run).
# ---------------------------------------------------------------------------

# The list of input feature columns the project models on. Order matters
# because downstream code indexes numpy arrays positionally.
FEATURE_COLUMNS: List[str] = [
    "Evapotranspiration",
    "Forest",
    "GRASS",
    "Crop",
    "Population",
    "Precipitation",
    "Temp_Mean",
    "Temp_Min",
    "Urban",
    "AreaBasin",
    "Lat",
]

# The regression target.
TARGET_COLUMN: str = "Lake_Area"

# Lake_Area values are large (km^2) — dividing by this constant keeps the
# loss values numerically tame during Transformer training. Predictions are
# multiplied back by this constant before being written to disk.
TARGET_RESCALE: int = 10_000


# ---------------------------------------------------------------------------
# Sub-config dataclasses
# ---------------------------------------------------------------------------

@dataclass
class TransformerConfig:
    """Architectural knobs for the 1D Transformer regressor.

    Defaults reproduce the values used in the original `src/config.py`.
    """

    # `dim_model` must match `len(FEATURE_COLUMNS)`; the model treats each
    # feature as one token along the sequence dimension.
    dim_model: int = len(FEATURE_COLUMNS)
    mlp_dim: int = 256
    num_heads: int = 1
    num_layers: int = 6
    dropout_rate: float = 0.3
    activation: str = "relu"
    num_class: int = 1  # regression -> single scalar output


@dataclass
class TrainingConfig:
    """Knobs that govern the training loop itself."""

    batch_size: int = 256
    learning_rate: float = 5e-3
    weight_decay: float = 5e-2
    epochs: int = 200

    # EarlyStopping triggers after `early_stop_patience` epochs without
    # improvement larger than `early_stop_min_delta`.
    early_stop_patience: int = 100
    early_stop_min_delta: float = 50.0

    # Dataloader parallelism. Set to 0 on Windows or in debug mode.
    num_workers: int = 8

    # Optional cap for fast iteration (None = use the full dataset). The
    # original `train.py` hard-coded this to 500 rows, which is a debug
    # artefact we no longer want by default.
    debug_row_limit: Optional[int] = None


@dataclass
class PathsConfig:
    """All paths used by the package.

    Defaults assume the user runs commands from the project root and wants
    outputs under `outputs/`. The CLI also passes overrides through, so this
    is just the fallback.
    """

    # Inputs
    data_csv: Path = Path("data/dataset.csv")
    lake_density_csv: Path = Path("data/Lake_Density_Edited.csv")

    # Output roots. *All* figures generated by the package end up under
    # `figures_dir` — that is the "specific folder for figures" requested by
    # the user.
    outputs_dir: Path = Path("outputs")
    figures_dir: Path = Path("outputs/figures")
    checkpoints_dir: Path = Path("outputs/checkpoints")
    predictions_dir: Path = Path("outputs/predictions")
    shap_dir: Path = Path("outputs/shap")

    def ensure(self) -> None:
        """Create any output directories that don't yet exist."""
        for p in (
            self.outputs_dir,
            self.figures_dir,
            self.checkpoints_dir,
            self.predictions_dir,
            self.shap_dir,
        ):
            Path(p).mkdir(parents=True, exist_ok=True)


@dataclass
class LakeConfig:
    """Top-level configuration object — what the rest of the package receives."""

    exp_name: str = "default"
    transformer: TransformerConfig = field(default_factory=TransformerConfig)
    training: TrainingConfig = field(default_factory=TrainingConfig)
    paths: PathsConfig = field(default_factory=PathsConfig)

    # ------------------------------------------------------------------
    # YAML loading / saving — handy for the CLI (`--config configs/foo.yaml`)
    # ------------------------------------------------------------------

    @classmethod
    def from_yaml(cls, yaml_path: str | Path) -> "LakeConfig":
        """Build a config from a YAML file, falling back to defaults for any
        keys the file omits.
        """
        with open(yaml_path, "r") as f:
            raw = yaml.safe_load(f) or {}

        cfg = cls()  # start from defaults

        # Apply scalar fields if present.
        if "exp_name" in raw:
            cfg.exp_name = raw["exp_name"]

        # Apply nested groups field-by-field so unknown keys raise.
        for section, sub in (
            ("transformer", cfg.transformer),
            ("training", cfg.training),
            ("paths", cfg.paths),
        ):
            for key, value in (raw.get(section) or {}).items():
                if not hasattr(sub, key):
                    raise KeyError(
                        f"Unknown key '{key}' in section '{section}' of {yaml_path}"
                    )
                # Path-valued fields should round-trip through `Path()`.
                if isinstance(getattr(sub, key), Path):
                    value = Path(value)
                setattr(sub, key, value)

        return cfg

    def to_dict(self) -> dict:
        """Serializable view of the config (Paths flattened to strings)."""
        d = asdict(self)
        # asdict() turns Path objects into Path() — re-stringify for YAML.
        d["paths"] = {k: str(v) for k, v in d["paths"].items()}
        return d


def default_config(exp_name: str = "default") -> LakeConfig:
    """Convenience factory — used by tests and notebook demos."""
    cfg = LakeConfig(exp_name=exp_name)
    return cfg
